In [ ]:
import numpy as np

**Q1: Questions on Basic NumPy Array**



(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
rev_arr = arr[::-1]
print(rev_arr)

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

flattened_arr = arr.flatten()

print(flattened_arr)


[1 2 3 2 4 5 1 2 3]


In [ ]:
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

flattened_arr = arr.ravel()

print(flattened_arr)

[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

elementwise_comparison = arr1 == arr2
print("Element-wise comparison:")
print(elementwise_comparison)

arrays_equal = np.array_equal(arr1, arr2)
print("Arrays are equal:", arrays_equal)

arrays_identical = arr1 is arr2
print("Arrays are the same object in memory:", arrays_identical)

Element-wise comparison:
[[ True  True]
 [False  True]]
Arrays are equal: False
Arrays are the same object in memory: False


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])


values, counts = np.unique(x, return_counts=True)

max_count_index = np.argmax(counts)
most_frequent_value = values[max_count_index]
most_frequent_count = counts[max_count_index]

indices = np.where(x == most_frequent_value)[0]

print("Most frequent value in x:", most_frequent_value)
print("Indices of most frequent value in x:", indices)


Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count_index = np.argmax(counts)
most_frequent_value = values[max_count_index]
most_frequent_count = counts[max_count_index]

indices = np.where(y == most_frequent_value)[0]

print("Most frequent value in y:", most_frequent_value)
print("Indices of most frequent value in y:", indices)

Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise  

iii. Sum of all elements column-wise

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = np.sum(gfg)
print("Sum of all elements:", total_sum)

row_sum = np.sum(gfg, axis=1)
print("Sum of all elements row-wise:", row_sum)

col_sum = np.sum(gfg, axis=0)
print("Sum of all elements column-wise:", col_sum)


Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [ ]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])


sum_diagonal = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal)

eigenvalues, _ = np.linalg.eig(n_array)
print("Eigenvalues of the matrix:", eigenvalues)

_, eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors of the matrix:\n", eigenvectors)

inverse_matrix = np.linalg.inv(n_array)
print("Inverse of the matrix:\n", inverse_matrix)

determinant = np.linalg.det(n_array)
print("Determinant of the matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]   
  
  q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]
   
   q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
import numpy as np

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1, q1)
print("Matrix multiplication of p1 and q1:\n", product1)

flattened_p1 = p1.flatten()
flattened_q1 = q1.flatten()
stacked_matrices1 = np.vstack([flattened_p1, flattened_q1])
covariance1 = np.cov(stacked_matrices1)
print("Covariance matrix of flattened p1 and q1:\n", covariance1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

product2 = np.dot(p2, q2)
print("Matrix multiplication of p2 and q2:\n", product2)

flattened_p2 = p2.flatten()
flattened_q2 = q2.flatten()
stacked_matrices2 = np.vstack([flattened_p2, flattened_q2])
covariance2 = np.cov(stacked_matrices2)
print("Covariance matrix of flattened p2 and q2:\n", covariance2)


Matrix multiplication of p1 and q1:
 [[16 19]
 [26 31]]
Covariance matrix of flattened p1 and q1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Matrix multiplication of p2 and q2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix of flattened p2 and q2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.dot(x, y.T)
print("Inner product:\n", inner_product)

x_flat = x.flatten()
y_flat = y.flatten()

outer_product = np.outer(x_flat, y_flat)
print("Outer product:\n", outer_product)

x_grid, y_grid = np.meshgrid(x_flat, y_flat, indexing='ij')
cartesian_product = np.stack((x_grid, y_grid), axis=-1)

print("Cartesian product:\n", cartesian_product)


Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[[ 2  1]
  [ 2  5]
  [ 2  0]
  [ 2  5]
  [ 2 10]
  [ 2  3]]

 [[ 3  1]
  [ 3  5]
  [ 3  0]
  [ 3  5]
  [ 3 10]
  [ 3  3]]

 [[ 4  1]
  [ 4  5]
  [ 4  0]
  [ 4  5]
  [ 4 10]
  [ 4  3]]

 [[ 3  1]
  [ 3  5]
  [ 3  0]
  [ 3  5]
  [ 3 10]
  [ 3  3]]

 [[ 2  1]
  [ 2  5]
  [ 2  0]
  [ 2  5]
  [ 2 10]
  [ 2  3]]

 [[ 9  1]
  [ 9  5]
  [ 9  0]
  [ 9  5]
  [ 9 10]
  [ 9  3]]]


**Q2: Based on NumPy Mathematics and Statistics**

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_array = np.abs(array)

flattened_array = array.flatten()

percentiles = {
    '25th': np.percentile(flattened_array, 25),
    '50th': np.percentile(flattened_array, 50),
    '75th': np.percentile(flattened_array, 75)
}

percentiles_columns = {
    '25th': np.percentile(array, 25, axis=0),
    '50th': np.percentile(array, 50, axis=0),
    '75th': np.percentile(array, 75, axis=0)
}

percentiles_rows = {
    '25th': np.percentile(array, 25, axis=1),
    '50th': np.percentile(array, 50, axis=1),
    '75th': np.percentile(array, 75, axis=1)
}

mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Element-wise Absolute Value:\n", abs_array)
print("\nPercentiles (Flattened Array):", percentiles)
print("Percentiles (Each Column):", percentiles_columns)
print("Percentiles (Each Row):", percentiles_rows)
print("\nMean (Flattened Array):", mean_flattened)
print("Median (Flattened Array):", median_flattened)
print("Standard Deviation (Flattened Array):", std_flattened)
print("Mean (Each Column):", mean_columns)
print("Median (Each Column):", median_columns)
print("Standard Deviation (Each Column):", std_columns)
print("Mean (Each Row):", mean_rows)
print("Median (Each Row):", median_rows)
print("Standard Deviation (Each Row):", std_rows)


Element-wise Absolute Value:
 [[1 2 3]
 [4 5 6]]

Percentiles (Flattened Array): {'25th': -3.5, '50th': -0.5, '75th': 2.5}
Percentiles (Each Column): {'25th': array([-2.75, -0.25, -3.75]), '50th': array([-1.5,  1.5, -1.5]), '75th': array([-0.25,  3.25,  0.75])}
Percentiles (Each Row): {'25th': array([-0.5, -5. ]), '50th': array([ 1., -4.]), '75th': array([2. , 0.5])}

Mean (Flattened Array): -0.5
Median (Flattened Array): -0.5
Standard Deviation (Flattened Array): 3.8622100754188224
Mean (Each Column): [-1.5  1.5 -1.5]
Median (Each Column): [-1.5  1.5 -1.5]
Standard Deviation (Each Column): [2.5 3.5 4.5]
Mean (Each Row): [ 0.66666667 -1.66666667]
Median (Each Row): [ 1. -4.]
Standard Deviation (Each Row): [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
import numpy as np

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)

ceiling_values = np.ceil(a)

truncated_values = np.trunc(a)

rounded_values = np.round(a)

print("Original array:", a)
print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)


Original array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


**Q3: Based on Searching and Sorting**

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [ ]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)

sorted_indices = np.argsort(array)

four_smallest_elements = sorted_array[:4]

five_largest_elements = sorted_array[-5:]

print("Sorted Array:", sorted_array)
print("Indices of Sorted Array:", sorted_indices)
print("4 Smallest Elements:", four_smallest_elements)
print("5 Largest Elements:", five_largest_elements)


Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [ ]:
import numpy as np

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_mask = (array == np.floor(array))
integer_elements = array[integer_mask]

float_mask = (array != np.floor(array))
float_elements = array[float_mask]

print("Integer Elements Only:", integer_elements)
print("Float Elements Only:", float_elements)

Integer Elements Only: [1. 2. 3. 2.]
Float Elements Only: [1.2 2.2]


**Q4:**

(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [3]:
import numpy as np
from PIL import Image

def img_to_array(path):
    img = Image.open(path)

    img_array = np.array(img)

    # text_file_path = path.rsplit('.', 1)[0] + '_array.txt'

    if len(img_array.shape) == 2:  # Grayscale
        file_name = "grayscale_image.txt"
        np.savetxt(file_name, img_array, fmt='%d')
        print(f"Grayscale image saved as {file_name}")
    elif len(img_array.shape) == 3 and img_array.shape[2] == 3:  # RGB
        file_name = "rgb_image.txt"
        np.savetxt(file_name, img_array.reshape(-1, 3), fmt='%d')
        print(f"RGB image saved as {file_name}")
    else:
        raise ValueError("Unsupported image format")

    print(f"Image data has been saved to {file_name}")


(b) Load the saved file into jupyter notebook?

In [4]:
img_to_array('/content/wp6991936.jpg')

RGB image saved as rgb_image.txt
Image data has been saved to rgb_image.txt
